In [25]:
def Leaders(arr,size):
    for i in range(0, size):
        j = i + 1
        is_leader = True
        
        while j < size:
            if arr[i]<=arr[j]:
                break
            j += 1
            
        if is_leader and j == size:
            print (arr[i],end=" ")
 
arr=[16, 1700000000000000000000000000000, 4, 3, 50000000000000000000000, 200000000000000000]
Leaders(arr, len(arr))

1700000000000000000000000000000 50000000000000000000000 200000000000000000 

In [2]:
import heapq

def minimize_curse(N, D, teachers):
    teachers.sort(key=lambda x: x[0])               

    min_curse = 0 
    lectures_heap = [] 
    day = 1  
    for i in range(N):
        while day < teachers[i][0]:
            if lectures_heap:
                curse, _, lectures = heapq.heappop(lectures_heap)
                min_curse += curse
                lectures -= 1
                if lectures > 0:
                    heapq.heappush(lectures_heap, (curse, day, lectures))
            day += 1
        heapq.heappush(lectures_heap, (teachers[i][2], day, teachers[i][1]))
        day += 1
    while day <= D and lectures_heap:
        curse, _, lectures = heapq.heappop(lectures_heap)
        min_curse += curse
        lectures -= 1
        if lectures > 0:
            heapq.heappush(lectures_heap, (curse, day, lectures))
        day += 1
    return min_curse
N, D = map(int, input().split())
teachers = []
for _ in range(N):
    Di, Ti, Si = map(int, input().split())
    teachers.append((Di, Ti, Si))
result = minimize_curse(N, D, teachers)
print(result)

2 3 
1 2 300
2 2 100
100


In [32]:
def zigzag(arr, n): 
  

    X = True
    for j in range(n - 1): 
  
       
        if X is True: 
  
            if arr[j] > arr[j + 1]: 
                arr[j], arr[j + 1] = arr[j + 1], arr[j] 
  
            else: 
  
             if arr[j] < arr[j + 1]: 
                arr[j], arr[j + 1] = arr[j + 1], arr[j] 
        X = bool(1 - X) 
    print(arr) 
  

arr = [4, 3, 7, 8, 6, 2, 1] 
n = len(arr) 
zigzag(arr, n) 


[3, 4, 8, 7, 2, 6, 1]


In [3]:
def Leader(arr,size):

    for i in range(0, size):
        for j in range(i+1, size):
            if arr[i]<=arr[j]:
                break
    if j == size-1: 
        print (arr[i],end=' ')

arr=[16, 17, 4,3,5,2]
Leader(arr, len(arr))

2 

In [31]:
def zigzag(arr, n): 
  

    X = True
    for i in range(n - 1): 
  
       
        if X is True: 
  
            if arr[i] > arr[i + 1]: 
                arr[i], arr[i + 1] = arr[i + 1], arr[i] 
  
            else: 
  
             if arr[i] < arr[i + 1]: 
                arr[i], arr[i + 1] = arr[i + 1], arr[i] 
        X = bool(1 - X) 
    print(arr) 
  

arr = [4, 3, 7, 8, 6, 2, 1] 
n = len(arr) 
zigzag(arr, n) 


[3, 4, 8, 7, 2, 6, 1]


In [35]:
def zigZag(arr, n):
    X = True
    for i in range(n - 1):
   
        if X is True:

            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
        else:

            if arr[i] < arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
        X = bool(1 - X)
    print(arr)

arr = [4, 3, 7, 8, 6, 2, 1]
n = len(arr)
zigZag(arr, n)

[3, 7, 4, 8, 2, 6, 1]


In [4]:
numRay = [1, 10, 11, 12, 11, 1]
arr_size = len(numRay)
for i in range(arr_size):

    x = numRay[i] % arr_size
    numRay[x] = numRay[x] + arr_size

print("The repeating elements are : ")
for i in range(arr_size):
    if (numRay[i] >= arr_size*2):
        print(i, " ")

The repeating elements are : 
1  
3  
4  
5  


In [5]:
numRay = [1, 10, 11, 12, 11, 1]
arr_size = len(numRay)
for i in range(arr_size):

    x = numRay[i] % arr_size
    numRay[x] = numRay[x] + arr_size

print("The repeating elements are : ")
for i in range(arr_size):
    if (numRay[i] >= arr_size*2):
        print(i, " ")

The repeating elements are : 
1  
3  
4  
5  


In [6]:
test_list = [1, 10, 11, 12, 11, 1]
print ("The original list is : "
        + str(test_list))

test_list = list(set(test_list))

print ("The list after removing duplicates : "
        + str(test_list))

The original list is : [1, 10, 11, 12, 11, 1]
The list after removing duplicates : [1, 10, 11, 12]


In [8]:
def mergeSort(arr):
    if len(arr) > 1:

        mid = len(arr)//2

        L = arr[:mid]

        R = arr[mid:]
    
        mergeSort(L)

        mergeSort(R)

        i = j = k = 0

        while i < len(L) and j < len(R):
            if L[i] <= R[j]:
                arr[k] = L[i]
                i += 1
            else:
                arr[k] = R[j]
            j += 1
            k += 1

        while i < len(L):
            arr[k] = L[i]
            i += 1
            k += 1

        while j < len(R):
            arr[k] = R[j]
            j += 1
            k += 1

def printList(arr):
    for i in range(len(arr)):
        print(arr[i], end=" ")
    print()

if __name__ == '__main__':
    arr = [12, 11, 13, 5, 6, 7]
    print("Given array is")
    printList(arr)
    mergeSort(arr)
    print("\nSorted array is ")
    printList(arr)

Given array is
12 11 13 5 6 7 

Sorted array is 
5 7 7 11 12 13 


In [54]:
import numpy as np

values = [0, 1, 2, 3,4, 5, 6, 7, 8]

x = np.array(values).reshape(3, 3)

print(x)
for i in range(3):
    for j in range(3):
        x[0][0],x[0][2]=x[0][2],x[0][0]
        x[2][0],x[2][2]=x[2][2],x[2][0]
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [3 4 5]
 [8 7 6]]


In [52]:
a=[[0,1,2],[3,4,5],[6,7,8]]
for i in range(len(a)):
    temp=a[i][0]
    a[i][0]=a[i][2]
    a[i][2]=temp
    
print(a)

[[2, 1, 0], [5, 4, 3], [8, 7, 6]]


In [53]:
import numpy as np
x = np.arange(1, 10).reshape(3, 3)

x
print(x)
for i in range(3):
    for j in range(3):
        if (i <3 and j ==2 ):
            print(x[i][j],end=" ")
print("")           
for i in range(3):
    for j in range(3):
        if (i <3 and j ==1 ):
            print(x[i][j],end=" ")
print("")            
for i in range(3):
    for j in range(3):
        if (i <3 and j ==0 ):
            print(x[i][j],end=" ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 6 9 
2 5 8 
1 4 7 

In [55]:
import numpy as np


values = [0, 1, 2, 3,4, 5, 6, 7, 8]


matrix = np.array(values).reshape(3, 3)

print(matrix)
for i in range(3):
    for j in range(3):
        matrix[0][0],matrix[0][2]=matrix[0][2],matrix[0][0]
        matrix[2][0],matrix[2][2]=matrix[2][2],matrix[2][0]
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [3 4 5]
 [8 7 6]]


In [75]:
test_list = [2, 3, 1, 0, 4, 5, 7, 6, 9, 8]

print("Original list is : " + str(test_list))

print("List index-value are : ")
for index, value in enumerate(test_list):
    print(index, value)

Original list is : [2, 3, 1, 0, 4, 5, 7, 6, 9, 8]
List index-value are : 
0 2
1 3
2 1
3 0
4 4
5 5
6 7
7 6
8 9
9 8


In [4]:
import heapq

def shortest_path(n, m, portals, unsafe_times):
    graph = [[] for _ in range(n + 1)]
    for a, b, c in portals:
        graph[a].append((b, c))
        graph[b].append((a, c))
    
    min_time = [-1] * (n + 1)
    min_time[1] = 0
    pq = [(0, 1)]

    while pq:
        time, current_universe = heapq.heappop(pq)
        
        if current_universe == n:
            return time

        if time > min_time[current_universe]:
            continue

        for neighbor, travel_time in graph[current_universe]:
            if time % 2 == 0:
                waiting_time = 0
            else:
                waiting_time = 1

            next_time = time + travel_time + waiting_time

            if min_time[neighbor] == -1 or next_time < min_time[neighbor]:
                min_time[neighbor] = next_time
                heapq.heappush(pq, (next_time, neighbor))

    return -1

if __name__ == "__main__":
    n, m = map(int, input().split())
    portals = []
    
    for _ in range(m):
        a, b, c = map(int, input().split())
        portals.append((a, b, c))
    
    unsafe_times = {}
    
    for i in range(1, n + 1):
        k_line = input().split()
        k = int(k_line[0])
        unsafe_times[i] = list(map(int, k_line[1:]))
    
    result = shortest_path(n, m, portals, unsafe_times)
    print(result)


4 4 
1 2 3
1 3 2
2 4 2
3 4 3
0
1 4
2 2 3
0
5


In [5]:
def find3Numbers(A, arr_size, sum):

    for i in range( 0, arr_size-2):

        for j in range(i + 1, arr_size-1):

            for k in range(j + 1, arr_size):
                if A[i] + A[j] + A[k] == sum:
                    print("Triplet is", A[i],
                        ", ", A[j], ", ", A[k])
                    return True

    return False

A = [12, 3, 4, 1, 6, 9]
sum = 24
arr_size = len(A)
find3Numbers(A, arr_size, sum)


Triplet is 12 ,  3 ,  9


True

In [6]:
def find3Numbers(A, arr_size, sum):

    for i in range( 0, arr_size-2):

        for j in range(i + 1, arr_size-1):

            
                if A[i] + A[j] == sum:
                    print("Square is", A[i],
                        ", ", A[j])
                    return True

    return False

A = [12, 3, 4, 1, 6, 9]
sum = 10
arr_size = len(A)
find3Numbers(A, arr_size, sum)

Square is 4 ,  6


True

In [7]:
def segregate0and1(arr, n) :

    count = 0

    for i in range(0, n) :
        if (arr[i] == 0) :
            count = count + 1

    for i in range(0, count) :
        arr[i] = 0

    for i in range(count, n) :
        arr[i] = 1

def print_arr(arr , n) :
    print( "after segregation it will be ",end = "")

    for i in range(0, n) :
        print(arr[i] , end = " ")

arr = [ 0, 1, 0, 1, 1, 1 ]
n = len(arr)

segregate0and1(arr, n)
print_arr(arr, n)


after segregation it will be 0 0 1 1 1 1 

In [8]:
v = [[0,6,0], [0,2,0], [8,4,0]]
n = len(v)

x = []
for i in range(n):
    for j in range(n):
        x.append(v[i][j])

x.sort()
k = 0
for i in range(n):
    for j in range(n):
        v[i][j] = x[k]
        k += 1

print("Sorted Matrix will be: ")
for i in range(n):
    for j in range(n):
        print(v[i][j], end=" ")
    print("")

Sorted Matrix will be: 
0 0 0 
0 0 2 
4 6 8 


In [9]:
v = [[0,6,0], [0,2,0], [8,4,0]]
n = len(v)

x = []
for i in range(n):
    for j in range(n):
        x.append(v[i][j])

x.sort()
k = 0
for i in range(n):
    for j in range(n):
        v[i][j] = x[k]
        k += 1

print("Sorted Matrix will be: ")
for i in range(n):
    for j in range(n):
        print(v[i][j], end=" ")
    print("")

Sorted Matrix will be: 
0 0 0 
0 0 2 
4 6 8 


In [10]:
v = [[7,6,5], [1,2,3], [8,4,9]]
n = len(v)

x = []
for i in range(n):
    for j in range(n):
        x.append(v[i][j])

x.sort()
k = 0
for i in range(n):
    for j in range(n):
        v[i][j] = x[k]
        k += 1

print("Sorted Matrix will be: ")
for i in range(n):
    for j in range(n):
        print(v[i][j], end=" ")
    print("")

Sorted Matrix will be: 
1 2 3 
4 5 6 
7 8 9 


In [11]:
v = [[7,6,5], [1,2,3], [8,4,9]]
n = len(v)

x = []
for i in range(n):
    for j in range(n):
        x.append(v[i][j])

x.sort()
k = 0
for i in range(n):
    for j in range(n):
        v[i][j] = x[k]
        k += 1

print("Sorted Matrix will be: ")
for i in range(n):
    for j in range(n):
        print(v[i][j], end=" ")
    print("")

Sorted Matrix will be: 
1 2 3 
4 5 6 
7 8 9 


In [12]:
def multiply(x,y):

    if(y == 0):
        return 0

    if(y > 0 ):
        return (x + multiply(x, y - 1))

    if(y < 0 ):
        return -multiply(x, -y)

print(multiply(7, 13))

91


In [13]:
#in a 4 x 4 matrix which row has maximum no of 1s 
R,C = 4,4

def first(arr , low , high):

    if(high >= low):

        mid = low + (high - low)//2

        if ( ( mid == 0 or arr[mid-1] == 0) and arr[mid] == 1):
            return mid
        
        elif (arr[mid] == 0):
            return first(arr, (mid + 1), high);

        else:
            return first(arr, low, (mid -1));

    return -1

def rowWithMax1s(mat):

    max_row_index,Max = 0,-1

    for i in range(R):

        index = first (mat[i], 0, C-1)
        if (index != -1 and C-index > Max):
            Max = C - index;
            max_row_index = i

    return max_row_index

mat = [[0, 0, 0, 1],
    [0, 1, 1, 1],
    [1, 1, 1, 1],
    [0, 0, 0, 0]]
print("Index of row with maximum 1s is " + str(rowWithMax1s(mat)))

Index of row with maximum 1s is 2
